"""
ReliAI -- FastAPI backend for the React frontend
====================================================
Thin HTTP wrapper around the existing pipeline code (schemas.py,
detection/, reasoning/, evaluation/, remediation/). No pipeline logic
lives here -- every endpoint either reads a saved artifact from disk or
calls straight into an existing function, so this file stays a pure
presentation-layer adapter, same spirit as remediation/app.py (which it
sits alongside, not replaces -- the Streamlit app still works standalone).

Two kinds of data are served:

1. Incident reports (schemas.IncidentReport) -- one full pipeline run's
   output: evidence events/graph, RCA hypotheses, remediation plan,
   verification result. Either loaded from a saved JSON file, or
   generated fresh on demand ("run live", stub LLM only -- see
   /api/reports/live's docstring for why real-LLM isn't wired there).

2. Benchmark comparison results (structured vs naive accuracy) -- these
   are read from a fixed JSON file under benchmark_results/, NOT
   generated by calling an LLM inside a request. A --real-llm benchmark
   run takes minutes and can hit free-tier rate limits (see
   evaluation/benchmark_runner.py's docstring); baking that into a web
   request would make the dashboard flaky and slow. Instead:
       python -m evaluation.benchmark_runner --real-llm --repeats 3 \
           --output benchmark_results/synthetic.json
       python -m evaluation.real_data_benchmark --real-llm --repeats 3 \
           --output benchmark_results/real_data.json
   regenerates the file whenever you want fresh numbers, and this API
   just serves whatever is currently on disk -- the same "load a saved
   snapshot" philosophy remediation/app.py already uses for reports.

Run with (from the project root, venv active):
    uvicorn api.main:app --reload --port 8000
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import ValidationError

from reasoning.evidence_graph import EvidenceGraphBuilder
from remediation.app import load_report
from remediation.pipeline_utils import get_llm, run_sample_incident
from schemas import IncidentReport

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BENCHMARK_RESULTS_DIR = PROJECT_ROOT / "benchmark_results"

# name -> (file path, display label). Add an entry here to expose another
# saved report in the frontend's report picker -- nothing else to wire up.
REPORTS: dict[str, tuple[Path, str]] = {
    "sample": (PROJECT_ROOT / "sample_report.json", "Sample incident (synthetic feature drift)"),
    "real-data": (
        PROJECT_ROOT / "adult_income_report.json",
        "Real Adult/Census data (stub LLM, 6 simultaneous failure types)",
    ),
    "real-data-llm": (
        PROJECT_ROOT / "adult_income_report_real_llm.json",
        "Real Adult/Census data (real Gemini, 6 simultaneous failure types)",
    ),
}

app = FastAPI(title="ReliAI API")

# Dev-friendly CORS: the frontend runs on a different port (Vite's 5173)
# during development. Tighten this if the API is ever exposed beyond
# localhost -- it's wide open here because both sides run on the same
# machine for a course demo, never on a public network.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def _report_to_dict(report: IncidentReport) -> dict:
    """IncidentReport as JSON, plus two fields the frontend needs that
    schemas.IncidentReport doesn't persist:

    - edges: EvidenceEdges recomputed from evidence_nodes via the same
      deterministic function remediation/app.py's Evidence Graph section
      uses (EvidenceGraphBuilder._build_edges) -- edges are a pure
      function of two nodes' timestamps/confidences plus the shared
      configs.settings.GRAPH thresholds, so this reproduces exactly the
      edges the original pipeline run computed, not invented data.
    - top_node_id: the top hypothesis's node_id, for the frontend to
      highlight in the graph view (same logic as remediation/app.py's
      render_report()).
    """
    data = json.loads(report.model_dump_json())
    edges = EvidenceGraphBuilder()._build_edges(report.evidence_nodes)
    data["edges"] = [json.loads(edge.model_dump_json()) for edge in edges]
    data["top_node_id"] = (
        report.rca_result.hypotheses[0].node_id if report.rca_result.hypotheses else None
    )
    data["root_cause_correct"] = (
        report.root_cause_correct() if report.ground_truth_label is not None else None
    )
    return data


def _report_summary(name: str, path: Path, label: str) -> Optional[dict]:
    if not path.exists():
        return None
    try:
        report = load_report(str(path))
    except (ValidationError, json.JSONDecodeError) as exc:
        logger.warning("Skipping unreadable report %s: %s", path, exc)
        return None
    return {
        "name": name,
        "label": label,
        "incident_id": report.incident_id,
        "detected_at": report.detected_at.isoformat(),
        "ground_truth_label": report.ground_truth_label.value if report.ground_truth_label else None,
        "root_cause_correct": (
            report.root_cause_correct() if report.ground_truth_label is not None else None
        ),
    }


@app.get("/api/health")
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/reports")
def list_reports() -> list[dict]:
    """Every saved report this API knows about, with just enough summary
    info for a picker UI -- not the full (potentially large) report."""
    summaries = [_report_summary(name, path, label) for name, (path, label) in REPORTS.items()]
    return [s for s in summaries if s is not None]


@app.get("/api/reports/{name}")
def get_report(name: str) -> dict:
    """One full IncidentReport, by the short name from /api/reports."""
    if name not in REPORTS:
        raise HTTPException(status_code=404, detail=f"Unknown report '{name}'")
    path, _label = REPORTS[name]
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Report file not found: {path.name}")
    try:
        report = load_report(str(path))
    except (ValidationError, json.JSONDecodeError) as exc:
        raise HTTPException(status_code=500, detail=f"Report file is invalid: {exc}") from exc
    return _report_to_dict(report)


@app.post("/api/reports/live")
def run_live_report() -> dict:
    """Generate a fresh synthetic injected-drift incident and run the full
    real pipeline (detection -> evidence graph -> RCA -> remediation ->
    verification) right now.

    Deliberately stub-LLM only, same as remediation/app.py's "Run live"
    mode: a request handler is the wrong place for a real Gemini call
    (adds seconds of latency, can 429/503 on the free tier, and ties the
    demo's reliability to network conditions). If a real-LLM live report
    is ever wanted, generate it offline with
    remediation/generate_sample_report.py and add it to REPORTS instead
    of calling the LLM inside this endpoint.
    """
    try:
        report: IncidentReport = run_sample_incident(llm=get_llm())
    except Exception as exc:  # pragma: no cover -- surfaced to the frontend, not swallowed
        logger.exception("Live pipeline run failed")
        raise HTTPException(status_code=500, detail=f"Pipeline run failed: {exc}") from exc
    return _report_to_dict(report)


def _read_benchmark_json(filename: str) -> dict:
    path = BENCHMARK_RESULTS_DIR / filename
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=(
                f"No benchmark results at {path.name} yet. Generate it with the matching "
                "evaluation script's --output flag (see api/main.py's module docstring)."
            ),
        )
    with path.open(encoding="utf-8") as f:
        return json.load(f)


@app.get("/api/benchmarks/synthetic")
def get_synthetic_benchmark() -> dict:
    """The 12-incident synthetic benchmark's structured-vs-naive result,
    as last saved by evaluation/benchmark_runner.py --output."""
    return _read_benchmark_json("synthetic.json")


@app.get("/api/benchmarks/real-data")
def get_real_data_benchmark() -> dict:
    """The 6-case real-data (Adult/Census) benchmark's structured-vs-naive
    result, as last saved by evaluation/real_data_benchmark.py --output."""
    return _read_benchmark_json("real_data.json")


@app.get("/api/benchmarks/ablation")
def get_ablation_benchmark() -> dict:
    """Detector ablation: accuracy with each detector disabled, as last
    saved by evaluation/real_data_benchmark.py --ablation --output."""
    return _read_benchmark_json("ablation.json")
